{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# load module and pre generate data\n",
    "from graph_tree_link_module import *\n",
    "\n",
    "import numpy as np\n",
    "\n",
    "import pickle\n",
    "\n",
    "# Open the file in binary read mode and load the object\n",
    "with open(\"graph_tree.pkl\", \"rb\") as file:\n",
    "    gt = pickle.load(file)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "sliders_data = [{\"id\": gt.attr_name[i], \"min\": gt.X_maxmin[1][i], \"max\": gt.X_maxmin[0][i], \"value\": gt.nodes[0].center[i], \"type\": \"f\"} for i in range(len(gt.attr_name))]\n",
    "# print(sliders_data)\n",
    "\n",
    "recom_data = [{\"i\": i, \"id\": gt.attr_name[i], \"max_val\": gt.recom[i][0].center[i], \"min_val\": gt.recom[i][1].center[i]} for i in range(len(gt.attr_name))]\n",
    "# print(recom_data)\n",
    "\n",
    "tree_data = {\n",
    "        \"name\": \"Root\",\n",
    "        \"children\": [\n",
    "            {\n",
    "                \"name\": \"Child 1\",\n",
    "                \"children\": [\n",
    "                    {\"name\": \"Grandchild 1\"},\n",
    "                    {\"name\": \"Grandchild 2\"}\n",
    "                ]\n",
    "            },\n",
    "            {\n",
    "                \"name\": \"Child 2\",\n",
    "                \"children\": [\n",
    "                    {\"name\": \"Grandchild 3\"},\n",
    "                    {\"name\": \"Grandchild 4\"}\n",
    "                ]\n",
    "            }\n",
    "        ]\n",
    "    }"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on http://127.0.0.1:8123\n",
      "Press CTRL+C to quit\n",
      "127.0.0.1 - - [27/Sep/2024 03:29:40] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:29:41] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:29:41] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:29:41] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:29:41] \"GET /static/graph_tree.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:29:41] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:29:41] \"GET /recom HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:29:41] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:29:41,216] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:29:41] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:29:45] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:30:20] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:30:20] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:30:20] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:30:20] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:30:20] \"GET /static/graph_tree.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:30:20] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:30:20] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:30:20,170] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:30:20] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:30:20] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:23] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:23] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:23] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:23] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:23] \"GET /static/graph_tree.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:23] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:23] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:33:23,159] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:23] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:23] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:32] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:32] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:32] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:32] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:32] \"GET /static/graph_tree.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:32] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:32] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:33:32,728] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:32] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:33:32] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:35:26] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:35:26] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:35:26] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:35:26] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:35:26] \"GET /static/graph_tree.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:35:26] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:35:26] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:35:26,710] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:35:26] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:35:26] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:00] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:00] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:00] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:00] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:00] \"GET /static/graph_tree.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:00] \"GET /sliders HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:36:00,376] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:00] \"GET /recom HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:00] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:00] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:07] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:07] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:07] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:07] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:07] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:07] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:36:08,003] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:36:08,725] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:36:08,934] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:08] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET /sliders HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:36:09,112] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET /recom HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:36:09,300] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:09] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:25] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:25] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:25] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:25] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:25] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:25] \"GET /static/graph_tree.js HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:36:25,688] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:25] \"GET /recom HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:25] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:25] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:28] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:28] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:28] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:28] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:28] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:28] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:28] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:36:28,918] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:28] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:28] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET /sliders HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:36:29,395] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET /recom HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:36:29,560] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:29] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:34] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:34] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:34] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:34] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:34] \"GET /static/graph_tree.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:34] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:34] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:36:34,501] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:34] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:34] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:40] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:40] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:40] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:40] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:40] \"GET /sliders HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:36:40,820] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:40] \"GET /recom HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:40] \"GET /static/graph_tree.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:40] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:40] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:36:53] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:50] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:50] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:50] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:50] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:50] \"GET /static/graph_tree.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:50] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:50] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:38:50,911] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:50] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:50] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:57] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:57] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:57] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:57] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:57] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:57] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:57] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:38:57,927] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:57] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:57] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /sliders HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:38:58,365] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /recom HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:38:58,547] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:38:58,708] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:38:58,899] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:58] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:59] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:59] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:59] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:59] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:59] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:59] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:38:59,057] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:59] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:38:59] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:39:07] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:39:07] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:39:07] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:39:07] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:39:07] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:39:07] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:39:07,765] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:39:07] \"GET /static/graph_tree.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:39:07] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:39:07] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:02] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:02] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:02] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:02] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:02] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:02] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:41:02,520] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:02] \"GET /static/graph_tree.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:02] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:02] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:41:03,255] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:41:03,444] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /sliders HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:41:03,598] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /recom HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:03] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:11] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:11] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:11] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:11] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:11] \"GET /static/graph_tree.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:11] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:11] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:41:11,779] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:11] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:41:11] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:37] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:37] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:37] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:37] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /static/graph_tree.js HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:42:38,039] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /recom HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:42:38,659] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /graph-data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /static/styles.css HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /static/scripts.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /static/curve_axis.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /static/graph_tree.js HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /sliders HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /recom HTTP/1.1\" 200 -\n",
      "[2024-09-27 03:42:38,848] ERROR in app: Exception on /graph-data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lst74\\AppData\\Local\\Temp\\ipykernel_11708\\3182419623.py\", line 49, in graph\n",
      "    return jsonify(graph_data)\n",
      "                   ^^^^^^^^^^\n",
      "NameError: name 'graph_data' is not defined\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /tree-data HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Sep/2024 03:42:38] \"GET /graph-data HTTP/1.1\" 500 -\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, render_template, request, jsonify\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "@app.route('/')\n",
    "def index():\n",
    "    return render_template('index.html')\n",
    "\n",
    "# slider ####################################################################\n",
    "@app.route('/sliders')\n",
    "def sliders():\n",
    "    return jsonify(sliders_data)\n",
    "\n",
    "@app.route('/handle_slider', methods=['POST'])\n",
    "def submit_slider_values():\n",
    "    data = request.json\n",
    "    print('Received slider values:', data)\n",
    "    query = np.array([float(val) for val in data.values()])\n",
    "    cur = gt.search(query)\n",
    "    print(cur.id)\n",
    "    print(gt.status)\n",
    "    global graph_data\n",
    "    graph_data = get_suround_node_data(gt.status)\n",
    "    # Process the data as needed\n",
    "    return jsonify({'status': 'slider respon success', 'received': data})\n",
    "# slider end ################################################################\n",
    "\n",
    "# recom ####################################################################\n",
    "@app.route('/recom')\n",
    "def recom():\n",
    "    return jsonify(recom_data)\n",
    "\n",
    "@app.route('/handle_recom', methods=['POST'])\n",
    "def handle_recom():\n",
    "    data = request.json\n",
    "    button_id = int(data.get('buttonId'))\n",
    "    val = int(data.get('val'))\n",
    "    print(button_id, val)\n",
    "    moved_node = gt.recom[button_id][val]\n",
    "    gt.get_suround_cluster(moved_node)\n",
    "    global graph_data\n",
    "    graph_data = get_suround_node_data(gt.status)\n",
    "    # Handle the button click based on the button_id\n",
    "    return jsonify({'status': 'recom respon success', 'buttonId': button_id, 'val': val, \"data\": graph_data})\n",
    "# recom end ####################################################################\n",
    "\n",
    "@app.route('/graph-data')\n",
    "def graph():\n",
    "    return jsonify(graph_data)\n",
    "\n",
    "@app.route('/tree-data')\n",
    "def tree():\n",
    "    return jsonify(tree_data)\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(port=8123)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
